service: medium

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless

functions:
  createPost:
    handler: handler.createPost
    events:
      - http:
          path: createPost
          method: post
